"""Database connection layer for SYTECH DEVICE TRACKING.

Uses PostgreSQL when DATABASE_URL is configured (Supabase/production) and
keeps SQLite as a zero-config local/test fallback.
"""
import os
import re
import sqlite3
from .contacts import normalize_contact

DB_PATH = os.environ.get("SYTECH_DB_PATH", os.path.join(os.path.dirname(__file__), "sytech.db"))
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
USING_POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))


def _pg_sql(sql: str) -> str:
    """Translate the small SQLite parameter/transaction syntax used by the app."""
    sql = sql.replace("BEGIN IMMEDIATE", "BEGIN")
    return sql.replace("?", "%s")


class PostgresCursor:
    def __init__(self, cursor, connection):
        self._cursor = cursor
        self._connection = connection

    def execute(self, sql, params=None):
        self._cursor.execute(_pg_sql(sql), params or ())
        return self

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    @property
    def lastrowid(self):
        # All callers use this immediately after inserting into an identity table.
        with self._connection._conn.cursor() as cur:
            cur.execute("SELECT lastval() AS id")
            row = cur.fetchone()
            return row["id"] if isinstance(row, dict) else row[0]

    def __iter__(self):
        return iter(self._cursor)


class PostgresConnection:
    def __init__(self, conn):
        self._conn = conn

    def cursor(self):
        return PostgresCursor(self._conn.cursor(), self)

    def execute(self, sql, params=None):
        cur = self.cursor()
        return cur.execute(sql, params)

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()


def get_db_connection():
    if USING_POSTGRES:
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:
            raise RuntimeError("DATABASE_URL is PostgreSQL but psycopg is not installed. Run: pip install -r requirements.txt") from exc
        return PostgresConnection(psycopg.connect(DATABASE_URL, row_factory=dict_row))

    conn = sqlite3.connect(DB_PATH, timeout=30.0, check_same_thread=False)
    conn.execute("PRAGMA busy_timeout=10000;")
    conn.execute("PRAGMA foreign_keys=ON;")
    conn.create_function("normalize_contact", 1, normalize_contact, deterministic=True)
    conn.row_factory = sqlite3.Row
    return conn


def _init_postgres():
    """Create/verify the Supabase-compatible schema. Safe to run repeatedly."""
    conn = get_db_connection()
    try:
        ddl = """
        CREATE TABLE IF NOT EXISTS users (
            user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            full_name_omang TEXT NOT NULL,
            primary_contact TEXT NOT NULL,
            alt_contact TEXT NOT NULL,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'customer' CHECK(role IN ('customer','operator','admin')),
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
        CREATE UNIQUE INDEX IF NOT EXISTS users_contact_unique ON users (lower(trim(primary_contact)));
        CREATE TABLE IF NOT EXISTS devices (
            device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
            device_type TEXT NOT NULL,
            brand TEXT NOT NULL,
            model TEXT NOT NULL,
            hardware_identifier TEXT UNIQUE NOT NULL,
            purchase_price_bwp NUMERIC(12,2) NOT NULL,
            success_fee_calculated NUMERIC(12,2) NOT NULL,
            is_registration_paid BOOLEAN DEFAULT FALSE,
            max_failed_logins INTEGER DEFAULT 3,
            local_bootloader_secured BOOLEAN DEFAULT TRUE,
            current_status TEXT DEFAULT 'secured',
            master_backup_pin TEXT DEFAULT '7924',
            created_at TIMESTAMPTZ DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS receipts (
            receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            device_id BIGINT REFERENCES devices(device_id) ON DELETE CASCADE,
            receipt_image_url TEXT NOT NULL,
            extracted_store_name TEXT,
            extracted_price_bwp NUMERIC(12,2),
            is_verified BOOLEAN DEFAULT FALSE,
            verified_by_operator_id BIGINT,
            uploaded_at TIMESTAMPTZ DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS tracking_intel (
            intel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            device_id BIGINT REFERENCES devices(device_id) ON DELETE CASCADE,
            trigger_type TEXT DEFAULT 'manual_cloud_flag',
            local_failed_attempts_logged INTEGER DEFAULT 0,
            captured_ip TEXT,
            captured_network_operator TEXT,
            new_sim_number_imsi TEXT,
            new_phone_number TEXT,
            nearby_wifi_macs TEXT,
            suspect_name_alias TEXT,
            suspect_social_links TEXT,
            suspect_photo_url TEXT,
            coarse_latitude NUMERIC(9,6),
            coarse_longitude NUMERIC(9,6),
            logged_at TIMESTAMPTZ DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS face_search_results (
            match_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            intel_id BIGINT REFERENCES tracking_intel(intel_id) ON DELETE CASCADE,
            scraped_source_url TEXT NOT NULL,
            confidence_score NUMERIC(5,2) NOT NULL,
            resolved_full_name TEXT,
            resolved_email TEXT,
            resolved_phone_link TEXT,
            scraped_at TIMESTAMPTZ DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS false_alarm_logs (
            log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            device_id BIGINT REFERENCES devices(device_id) ON DELETE CASCADE,
            cleared_via_method TEXT NOT NULL,
            attempts_before_clear INTEGER NOT NULL,
            logged_at TIMESTAMPTZ DEFAULT NOW()
        );
        CREATE TABLE IF NOT EXISTS financial_invoices (
            invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            device_id BIGINT REFERENCES devices(device_id) ON DELETE CASCADE,
            selected_service TEXT NOT NULL,
            base_amount NUMERIC(12,2) NOT NULL,
            deferred_reg_amount NUMERIC(12,2) DEFAULT 0.00,
            total_due NUMERIC(12,2) NOT NULL,
            is_settled BOOLEAN DEFAULT FALSE,
            payment_method TEXT,
            gateway_reference TEXT UNIQUE,
            settled_at TIMESTAMPTZ
        );
        CREATE TABLE IF NOT EXISTS checkout_requests (
            user_id BIGINT NOT NULL REFERENCES users(user_id),
            request_key TEXT NOT NULL,
            request_payload TEXT NOT NULL,
            invoice_id BIGINT NOT NULL REFERENCES financial_invoices(invoice_id),
            PRIMARY KEY (user_id, request_key)
        );
        CREATE INDEX IF NOT EXISTS idx_devices_user_id ON devices(user_id);
        CREATE INDEX IF NOT EXISTS idx_tracking_intel_device_id ON tracking_intel(device_id);
        CREATE INDEX IF NOT EXISTS idx_tracking_intel_logged_at ON tracking_intel(logged_at DESC);
        CREATE INDEX IF NOT EXISTS idx_receipts_device_id ON receipts(device_id);
        CREATE INDEX IF NOT EXISTS idx_invoices_device_id ON financial_invoices(device_id);
        """
        # psycopg accepts the DDL batch as one command in normal protocol.
        conn.execute(ddl)
        conn.commit()
    finally:
        conn.close()


def _init_sqlite():
    os.makedirs(os.path.dirname(os.path.abspath(DB_PATH)), exist_ok=True)
    conn = get_db_connection()
    conn.execute("PRAGMA journal_mode=WAL;")
    cursor = conn.cursor()
    cursor.execute("""CREATE TABLE IF NOT EXISTS users (user_id INTEGER PRIMARY KEY AUTOINCREMENT, full_name_omang TEXT NOT NULL, primary_contact TEXT NOT NULL, alt_contact TEXT NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'customer' CHECK(role IN ('customer','operator','admin')), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""")
    user_columns = {row[1] for row in cursor.execute("PRAGMA table_info(users)").fetchall()}
    if "role" not in user_columns:
        cursor.execute("ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'customer'")
    cursor.execute("""CREATE TABLE IF NOT EXISTS devices (device_id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE, device_type TEXT NOT NULL, brand TEXT NOT NULL, model TEXT NOT NULL, hardware_identifier TEXT UNIQUE NOT NULL, purchase_price_bwp REAL NOT NULL, success_fee_calculated REAL NOT NULL, is_registration_paid BOOLEAN DEFAULT 0, max_failed_logins INTEGER DEFAULT 3, local_bootloader_secured BOOLEAN DEFAULT 1, current_status TEXT DEFAULT 'secured', master_backup_pin TEXT DEFAULT '7924', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS receipts (receipt_id INTEGER PRIMARY KEY AUTOINCREMENT, device_id INTEGER REFERENCES devices(device_id) ON DELETE CASCADE, receipt_image_url TEXT NOT NULL, extracted_store_name TEXT, extracted_price_bwp REAL, is_verified BOOLEAN DEFAULT 0, verified_by_operator_id INTEGER NULL, uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS tracking_intel (intel_id INTEGER PRIMARY KEY AUTOINCREMENT, device_id INTEGER REFERENCES devices(device_id) ON DELETE CASCADE, trigger_type TEXT DEFAULT 'manual_cloud_flag', local_failed_attempts_logged INTEGER DEFAULT 0, captured_ip TEXT NULL, captured_network_operator TEXT NULL, new_sim_number_imsi TEXT NULL, new_phone_number TEXT NULL, nearby_wifi_macs TEXT NULL, suspect_name_alias TEXT NULL, suspect_social_links TEXT NULL, suspect_photo_url TEXT NULL, coarse_latitude REAL NULL, coarse_longitude REAL NULL, logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS face_search_results (match_id INTEGER PRIMARY KEY AUTOINCREMENT, intel_id INTEGER REFERENCES tracking_intel(intel_id) ON DELETE CASCADE, scraped_source_url TEXT NOT NULL, confidence_score REAL NOT NULL, resolved_full_name TEXT NULL, resolved_email TEXT NULL, resolved_phone_link TEXT NULL, scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS false_alarm_logs (log_id INTEGER PRIMARY KEY AUTOINCREMENT, device_id INTEGER REFERENCES devices(device_id) ON DELETE CASCADE, cleared_via_method TEXT NOT NULL, attempts_before_clear INTEGER NOT NULL, logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS financial_invoices (invoice_id INTEGER PRIMARY KEY AUTOINCREMENT, device_id INTEGER REFERENCES devices(device_id) ON DELETE CASCADE, selected_service TEXT NOT NULL, base_amount REAL NOT NULL, deferred_reg_amount REAL DEFAULT 0.00, total_due REAL NOT NULL, is_settled BOOLEAN DEFAULT 0, payment_method TEXT NULL, gateway_reference TEXT UNIQUE NULL, settled_at TIMESTAMP NULL)""")
    duplicates = cursor.execute("SELECT 1 FROM users GROUP BY normalize_contact(primary_contact) HAVING COUNT(*) > 1 LIMIT 1").fetchone()
    if duplicates or cursor.execute("PRAGMA foreign_key_check").fetchone():
        conn.rollback(); conn.close()
        raise RuntimeError("Database migration requires review: duplicate account contacts or orphaned records exist. Back up and repair the database before restarting.")
    cursor.execute("CREATE UNIQUE INDEX IF NOT EXISTS users_contact_unique ON users(normalize_contact(primary_contact))")
    cursor.execute("""CREATE TABLE IF NOT EXISTS checkout_requests (user_id INTEGER NOT NULL REFERENCES users(user_id), request_key TEXT NOT NULL, request_payload TEXT NOT NULL, invoice_id INTEGER NOT NULL REFERENCES financial_invoices(invoice_id), PRIMARY KEY (user_id, request_key))""")
    conn.commit(); conn.close()


def init_db():
    if USING_POSTGRES:
        _init_postgres()
    else:
        _init_sqlite()


if __name__ == "__main__":
    init_db()
    print("SYTECH database initialized successfully using", "PostgreSQL" if USING_POSTGRES else "SQLite")
